export enum LeadStatus {
  DISCOVERED = 'DISCOVERED',
  ENRICHED = 'ENRICHED',
  APPROVED_BY_HUNTER = 'APPROVED_BY_HUNTER',
  REJECTED_BY_HUNTER = 'REJECTED_BY_HUNTER',
  OUTREACH_GENERATED = 'OUTREACH_GENERATED',
  CONTACTED = 'CONTACTED',
  POSITIVE_REPLY = 'POSITIVE_REPLY',
  MEETING_SCHEDULED = 'MEETING_SCHEDULED',
  OPT_OUT_HALTED = 'OPT_OUT_HALTED',
  DISCARDED = 'DISCARDED'
}

export enum RecommendationBadge {
  PRIORITIZE = 'PRIORITIZE',
  REVIEW = 'REVIEW',
  DISCARD = 'DISCARD'
}
